import pandas as pd
import numpy as np

from aden_tools.tools.office_tool.schemas import (
    ExcelSchema,
    SheetData,
    ChartConfig,
    PresentationSchema,
    Slide,
    Bullet,
    ChartData,
    TableSlideData,
)

from aden_tools.tools.office_tool.excel_core import generate_excel
from aden_tools.tools.office_tool.powerpoint_core import generate_presentation


# ==========================================================
# Agent 1 — Researcher (Deterministic Mock Data)
# ==========================================================

def fetch_data():
    np.random.seed(42)

    dates = pd.date_range(end=pd.Timestamp.today(), periods=30)

    data = pd.DataFrame({
        "AAPL": np.linspace(150, 165, 30) + np.random.normal(0, 2, 30),
        "MSFT": np.linspace(300, 320, 30) + np.random.normal(0, 3, 30),
    }, index=dates)

    return data


# ==========================================================
# Agent 2 — Analyst
# ==========================================================

def calculate_metrics(data: pd.DataFrame):

    returns = data.pct_change().dropna()

    cumulative = (1 + returns).cumprod()

    drawdown = cumulative / cumulative.cummax() - 1

    max_drawdown = drawdown.min()

    summary = {
        "AAPL Max Drawdown (%)": round(max_drawdown["AAPL"] * 100, 2),
        "MSFT Max Drawdown (%)": round(max_drawdown["MSFT"] * 100, 2),
    }

    return drawdown, summary


# ==========================================================
# Agent 3 — Reporter
# ==========================================================

def generate_excel_report(data):

    rows = []

    for date in data.index:
        rows.append({
            "Date": str(date.date()),
            "AAPL": round(float(data.loc[date]["AAPL"]), 2),
            "MSFT": round(float(data.loc[date]["MSFT"]), 2),
        })

    excel_schema = ExcelSchema(
        file_name="weekly_finance_data",
        sheets=[
            SheetData(
                name="Prices",
                rows=rows,
                charts=[
                    ChartConfig(
                        chart_type="line",
                        x_column="Date",
                        y_columns=["AAPL", "MSFT"],
                        title="Price Comparison"
                    )
                ]
            )
        ]
    )

    return generate_excel(excel_schema)


def generate_ppt_report(data, summary):

    categories = [str(d.date()) for d in data.index]

    ppt_schema = PresentationSchema(
        file_name="weekly_report",
        footer_text="Generated by Hive Office Pack",
        slides=[
            Slide(
                title="AAPL vs MSFT — Monthly Analysis",
                layout="title"
            ),
            Slide(
                title="Price Trend",
                chart=ChartData(
                    chart_type="line",
                    categories=categories,
                    series={
                        "AAPL": list(data["AAPL"].round(2)),
                        "MSFT": list(data["MSFT"].round(2)),
                    }
                )
            ),
            Slide(
                    title="Drawdown Summary",
                    table=TableSlideData(
                        headers=["Metric", "Value (%)"],
                        rows=[
                            [
                                "AAPL Max Drawdown",
                                f"{summary['AAPL Max Drawdown (%)']}%",
                            ],
                            [
                                "MSFT Max Drawdown",
                                f"{summary['MSFT Max Drawdown (%)']}%",
                            ],
                        ],
                    ),
                ),
            Slide(
                title="Key Insights",
                bullets=[
                    Bullet(text="AAPL showed moderate volatility."),
                    Bullet(text="MSFT maintained steady growth."),
                ]
            ),
            Slide(
                title="Conclusion",
                bullets=[
                    Bullet(text="Diversification reduces risk."),
                ]
            ),
        ],
    )

    return generate_presentation(ppt_schema)


# ==========================================================
# Run Full Workflow
# ==========================================================

if __name__ == "__main__":

    print("Generating deterministic market data...")
    data = fetch_data()

    print("Calculating drawdown metrics...")
    drawdown, summary = calculate_metrics(data)

    print("Generating Excel report...")
    excel_path = generate_excel_report(data)

    print("Generating PowerPoint report...")
    ppt_path = generate_ppt_report(data, summary)

    print("\n✅ Reports generated:")
    print("Excel:", excel_path)
    print("PowerPoint:", ppt_path)
