#!/bin/bash
#
# setup-codex.sh - Configure Codex CLI for Hive agent building
#
# This script:
# 1. Installs skills to ~/.codex/skills/ (same as quickstart.sh does for Claude)
# 2. Generates .codex/config.toml with MCP server paths
# 3. Verifies Python packages are installed
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Codex directories
CODEX_SKILLS_DIR="$HOME/.codex/skills"
CODEX_CONFIG_DIR="$PROJECT_ROOT/.codex"

echo ""
echo "=================================================="
echo "  Hive Agent Framework - Codex CLI Setup"
echo "=================================================="
echo ""

# ============================================================
# Step 1: Check Prerequisites
# ============================================================

echo -e "${BLUE}Step 1: Checking prerequisites...${NC}"
echo ""

# Check if codex is installed
if command -v codex &> /dev/null; then
    CODEX_VERSION=$(codex --version 2>/dev/null || echo "unknown")
    echo -e "${GREEN}  ✓ Codex CLI found: $CODEX_VERSION${NC}"
else
    echo -e "${YELLOW}  ⚠ Codex CLI not found${NC}"
    echo "    Install from: https://developers.openai.com/codex/cli/"
    echo "    Continuing with setup anyway..."
fi

# Check Python
if ! command -v python &> /dev/null && ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: Python is not installed.${NC}"
    exit 1
fi
echo -e "${GREEN}  ✓ Python found${NC}"

echo ""

# ============================================================
# Step 2: Install Skills to ~/.codex/skills/
# ============================================================

echo -e "${BLUE}Step 2: Installing skills to ~/.codex/skills/...${NC}"
echo ""

# Check if source skills exist
if [ ! -d "$PROJECT_ROOT/.claude/skills" ]; then
    echo -e "${RED}Error: Skills not found at $PROJECT_ROOT/.claude/skills${NC}"
    exit 1
fi

# Create Codex skills directory
mkdir -p "$CODEX_SKILLS_DIR"

# Function to install a skill
install_skill() {
    local skill_name=$1
    local source_dir="$PROJECT_ROOT/.claude/skills/$skill_name"
    local target_dir="$CODEX_SKILLS_DIR/$skill_name"

    if [ ! -d "$source_dir" ]; then
        echo -e "${YELLOW}  ⚠ Skill not found: $skill_name${NC}"
        return 1
    fi

    # Remove existing and copy fresh
    if [ -d "$target_dir" ]; then
        rm -rf "$target_dir"
    fi

    cp -r "$source_dir" "$target_dir"
    echo -e "${GREEN}  ✓ Installed: $skill_name${NC}"
}

# Install all skills
install_skill "building-agents-core"
install_skill "building-agents-construction"
install_skill "building-agents-patterns"
install_skill "testing-agent"
install_skill "agent-workflow"

echo ""

# ============================================================
# Step 3: Generate MCP Configuration
# ============================================================

echo -e "${BLUE}Step 3: Generating MCP configuration...${NC}"
echo ""

# Create .codex directory for config
mkdir -p "$CODEX_CONFIG_DIR"

# Generate config.toml with absolute paths
cat > "$CODEX_CONFIG_DIR/config.toml" << EOF
# Hive Agent Builder - Codex CLI MCP Configuration
# Generated by setup-codex.sh on $(date)
#
# Re-run ./scripts/setup-codex.sh if you move the project.

[mcp_servers.agent-builder]
command = "python"
args = ["-m", "framework.mcp.agent_builder_server"]
cwd = "$PROJECT_ROOT/core"
env = { PYTHONPATH = "$PROJECT_ROOT/tools/src" }

[mcp_servers.hive-tools]
command = "python"
args = ["mcp_server.py", "--stdio"]
cwd = "$PROJECT_ROOT/tools"
env = { PYTHONPATH = "src" }
EOF

echo -e "${GREEN}  ✓ Generated .codex/config.toml${NC}"
echo ""

# ============================================================
# Step 4: Verify Python Packages
# ============================================================

echo -e "${BLUE}Step 4: Verifying Python packages...${NC}"
echo ""

PYTHON_CMD="python3"
if ! command -v python3 &> /dev/null; then
    PYTHON_CMD="python"
fi

INSTALL_NEEDED=0

# Check framework
if $PYTHON_CMD -c "import framework" > /dev/null 2>&1; then
    echo -e "${GREEN}  ✓ framework package OK${NC}"
else
    echo -e "${YELLOW}  ⚠ framework not installed${NC}"
    INSTALL_NEEDED=1
fi

# Check aden_tools
if $PYTHON_CMD -c "import aden_tools" > /dev/null 2>&1; then
    echo -e "${GREEN}  ✓ aden_tools package OK${NC}"
else
    echo -e "${YELLOW}  ⚠ aden_tools not installed${NC}"
    INSTALL_NEEDED=1
fi

if [ $INSTALL_NEEDED -eq 1 ]; then
    echo ""
    echo -e "${YELLOW}  Some packages missing. Install with:${NC}"
    echo "    pip install -e $PROJECT_ROOT/core/"
    echo "    pip install -e $PROJECT_ROOT/tools/"
fi

echo ""

# ============================================================
# Step 5: Verify AGENTS.md exists
# ============================================================

echo -e "${BLUE}Step 5: Checking AGENTS.md...${NC}"
echo ""

if [ -f "$PROJECT_ROOT/AGENTS.md" ]; then
    echo -e "${GREEN}  ✓ AGENTS.md found at project root${NC}"
else
    echo -e "${YELLOW}  ⚠ AGENTS.md not found - Codex may not have project context${NC}"
fi

echo ""

# ============================================================
# Done
# ============================================================

echo "=================================================="
echo -e "${GREEN}  ✓ Codex CLI Setup Complete!${NC}"
echo "=================================================="
echo ""
echo "Installed:"
echo "  Skills:  $CODEX_SKILLS_DIR/"
echo "  Config:  $CODEX_CONFIG_DIR/config.toml"
echo "  Context: $PROJECT_ROOT/AGENTS.md"
echo ""
echo "Skills available:"
echo "  • building-agents-core"
echo "  • building-agents-construction"
echo "  • building-agents-patterns"
echo "  • testing-agent"
echo "  • agent-workflow"
echo ""
echo "Usage:"
echo "  ${BLUE}cd $PROJECT_ROOT${NC}"
echo "  ${BLUE}codex${NC}"
echo ""
echo "Then ask:"
echo "  ${BLUE}\"Using building-agents-construction, build me a research agent\"${NC}"
echo ""
