import os
import pytest

from aden_tools.tools.office_tool.schemas import (
    PresentationSchema,
    Slide,
    Bullet,
    ChartData,
    TableSlideData,
    ExcelSchema,
    SheetData,
    ColumnFormat,
    ConditionalFormat,
    ChartConfig,
    WordSchema,
    Paragraph,
)

from aden_tools.tools.office_tool.powerpoint_core import generate_presentation
from aden_tools.tools.office_tool.excel_core import generate_excel
from aden_tools.tools.office_tool.word_core import generate_word


# =====================================================
# PowerPoint Tests
# =====================================================

def test_powerpoint_generation_with_chart_and_table():

    schema = PresentationSchema(
        file_name="test_ppt",
        footer_text="Finance Team",
        slides=[
            Slide(
                title="Chart Slide",
                chart=ChartData(
                    chart_type="line",
                    categories=["A", "B", "C"],
                    series={"Series1": [1, 2, 3]},
                ),
                notes="Test Notes",
            ),
            Slide(
                title="Table Slide",
                table=TableSlideData(
                    headers=["Metric", "Value"],
                    rows=[["Revenue", "1000"], ["Profit", "400"]],
                ),
            ),
        ],
    )

    path = generate_presentation(schema)

    assert os.path.exists(path)
    assert path.endswith(".pptx")
    assert os.path.getsize(path) > 0


def test_powerpoint_invalid_chart_length():

    schema = PresentationSchema(
        file_name="bad_ppt",
        slides=[
            Slide(
                title="Bad Chart",
                chart=ChartData(
                    chart_type="line",
                    categories=["A", "B"],
                    series={"Series1": [1, 2, 3]},  # mismatch
                ),
            )
        ],
    )

    with pytest.raises(ValueError):
        generate_presentation(schema)


# =====================================================
# Excel Tests
# =====================================================

def test_excel_generation_full_features():

    schema = ExcelSchema(
        file_name="test_excel",
        sheets=[
            SheetData(
                name="Sheet1",
                rows=[
                    {"Month": "Jan", "Revenue": 100, "Cost": 50, "Profit": "=B2-C2"},
                    {"Month": "Feb", "Revenue": 200, "Cost": 80, "Profit": "=B3-C3"},
                ],
                formula_columns=["Profit"],
                column_formats=[
                    ColumnFormat(column="Revenue", number_format="$#,##0"),
                ],
                conditional_formats=[
                    ConditionalFormat(column="Profit", type="less_than", value=60),
                ],
                charts=[
                    ChartConfig(
                        chart_type="line",
                        x_column="Month",
                        y_columns=["Revenue"],
                    )
                ],
            )
        ],
    )

    path = generate_excel(schema)

    assert os.path.exists(path)
    assert path.endswith(".xlsx")
    assert os.path.getsize(path) > 0


def test_excel_invalid_formula_column():

    schema = ExcelSchema(
        file_name="bad_excel",
        sheets=[
            SheetData(
                name="Sheet1",
                rows=[{"A": 1, "B": 2}],
                formula_columns=["MissingColumn"],
            )
        ],
    )

    with pytest.raises(ValueError):
        generate_excel(schema)


# =====================================================
# Word Tests
# =====================================================

def test_word_generation_full_features():

    schema = WordSchema(
        file_name="test_word",
        header_text="Confidential",
        footer_text="Generated by Hive",
        paragraphs=[
            Paragraph(text="Main Title", heading_level=1),
            Paragraph(text="Bullet 1", list_type="bullet"),
            Paragraph(text="Bullet 2", list_type="numbered"),
            Paragraph(text="New Section", page_break_before=True),
        ],
    )

    path = generate_word(schema)

    assert os.path.exists(path)
    assert path.endswith(".docx")
    assert os.path.getsize(path) > 0


def test_word_invalid_image():

    schema = WordSchema(
        file_name="bad_word",
        paragraphs=[Paragraph(text="Hello")],
        images=[{"path": "non_existent_image.png"}],
    )

    with pytest.raises(Exception):
        generate_word(schema)
